#!/bin/bash
arch=$(getconf LONG_BIT)
kernel=$(uname)

if [ $kernel == "Darwin" ]; then
    echo "OSX"
    curl -o chromedriver.zip -O https://chromedriver.storage.googleapis.com/2.31/chromedriver_mac64.zip
    wget -O firefoxdriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz
else
    if [ $arch == "64" ]; then
        curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
        wget -O firefoxdriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    else
        curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux32.zip
        wget -O firefoxdriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux32.tar.gz
    fi
fi

unzip chromedriver.zip
rm chromedriver.zip
chmod +x chromedriver
mkdir -p assets/chrome
mv chromedriver ./assets/chrome/chromedriver

tar -xvf firefoxdriver.tar.gz
rm firefoxdriver.tar.gz
mkdir -p assets/firefox
mv geckodriver ./assets/firefox/geckodriver